"""Daily email digest — shows inbox/review folder counts across all accounts."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from openclaw_mail.config import REPORT_DIR, get_active_accounts
from openclaw_mail.utils.himalaya import get_envelopes
from openclaw_mail.utils.logging import get_logger

log = get_logger("digest", "digest.log")

REVIEW_FOLDER = "Review"


def get_folder_count(account_name: str, folder: str) -> int:
    envelopes = get_envelopes(account_name, folder, limit=500, timeout=30)
    return len(envelopes)


def generate_digest() -> str:
    now = datetime.now()
    lines = [
        f"# Daily Email Digest — {now.strftime('%B %d, %Y %H:%M')}",
        "",
    ]

    accounts = get_active_accounts()
    total_review = 0
    total_inbox = 0

    for acc in accounts:
        name = acc.get("himalaya_name", acc["id"])
        inbox_count = get_folder_count(name, "INBOX")
        review_count = get_folder_count(name, REVIEW_FOLDER)

        total_inbox += inbox_count
        total_review += review_count

        lines.append(f"## {acc['name']}")
        lines.append(f"- Inbox: {inbox_count}")
        lines.append(f"- Review: {review_count}")

        if review_count > 0:
            recent = get_envelopes(name, REVIEW_FOLDER, limit=5)
            for env in recent:
                subj = env.get("subject", "")[:50]
                lines.append(f"  - {subj}...")

        lines.append("")

    lines.append("---")
    lines.append(f"**Totals:** Inbox: {total_inbox} | Review: {total_review}")

    if total_review > 10:
        lines.append("")
        lines.append("**Action needed:** Many emails in Review folders!")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by openclaw-mail-agent*")
    return "\n".join(lines)


def save_digest() -> Path:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    text = generate_digest()

    latest = REPORT_DIR / "last_digest.md"
    latest.write_text(text)

    now = datetime.now()
    timestamped = REPORT_DIR / f"digest_{now.strftime('%Y%m%d_%H%M%S')}.md"
    timestamped.write_text(text)

    log.info(f"Digest saved to {latest}")
    return latest
